from . import day_01
from . import day_02
from . import day_03
from . import day_04
from . import day_05
from . import day_06
from . import day_07
from . import day_08
from . import day_09
from . import day_10
from . import day_11
from . import day_12
from . import day_13
from . import day_14
from . import day_15
from . import day_16
from . import day_17
from . import day_18
from . import day_19
from . import day_20
from . import day_21
